### ISSUE TITLE
Universal-Updater 3DSX file not showing up in homebrew launcher

### ISSUE THREAD

**Issue by Ne0nHoriz0n** [Universal-Team/Universal-Updater#102]
**Does not show up in homebrew launcher**

**To Reproduce:**
1. Download 3DSX version of universal-updater
2. put the 3dsx file into the 3ds folder in your sd card
3. open up the homebrew launcher and you will see it is not there

**I thought I would see the app in the homebrew launcher and be able to open it just like the .cia version.**

**Screenshots:
(i dont think i need any)**

**Console:**
- [ ] 3DS
- [ ] 3DS XL
- [ ] 2DS
- [ ] New 3DS
- [x] New 3DS XL
- [ ] New 2DS XL

**Luma3DS & System versions:**

Luma 3DS version: v10.2.1

System version and region: 11.15 USA

**Universal-Updater version:**

Release: v3.2.3

Nightly: 

Installed as:
- [ ] CIA
- [x] 3DSX

**Additional context:**

**Comment by Epicpkmn11** [comment]
Solved on Discord, closing.
