### ISSUE TITLE
[Feature Request] Download Retries

### ISSUE THREAD

**Issue by PabloX-del** [Universal-Team/Universal-Updater#109]
Please you added a download retries, like homebrew browser.
And also it would be nice to be able to download a homebrew when closing the console, as this is currently not possible.

**Comment by PabloX-del** [comment]
Like this for download retries :
![image](https://user-images.githubusercontent.com/85699648/143109424-ac6f8135-471a-4fab-a611-9bfb6a9f9ecf.png)

**Comment by PabloX-del** [comment]
Isn't that a good idea because I still don't have an answer?

**Comment by PabloX-del** [comment]
This should be possible with something like the following:
``while (i == false)
{
     If (downladFile() == true)
           i = true;

      Else
           Timer (10000);
}``

**Comment by NightScript370** [comment]
You clearly have no idea how software development works, nor will we allow issues created by people who steal our software to persist on our github. Goodbye, and don't come back.

**Comment by NightScript370** [comment]
Actually, no. Since you're such a Mr Wise Guy, how about you implement the code you sent us, and make a pull request?

**Comment by PabloX-del** [comment]
the code I sent you will not work on this homebrew at the level of the download.cpp, because it is not precisely that which it is necessary to put, I make a little cpp but not yet enough to modify Universal-Updater, the example which I give above is really very basic.

**Comment by arkomega1** [comment]
> You clearly have no idea how software development works, nor will we allow issues created by people who steal our software to persist on our github. Goodbye, and don't come back.

Ghost eShop be like

**Comment by Dhalian** [comment]
loooooooooooooool, this legendary discretion of the """"creator"""".

**Comment by PabloX-del** [comment]
> > You clearly have no idea how software development works, nor will we allow issues created by people who steal our software to persist on our github. Goodbye, and don't come back.
> 
> Ghost eShop be like

? You speaking about what ?

**Comment by LightSage** [comment]
[Your code crashes uu](https://i.imgur.com/kQUG6pq.png)
