### ISSUE TITLE
[Bug Report] app_name.ext failed!

### ISSUE THREAD

**Issue by logixhot** [Universal-Team/Universal-Updater#110]
**Describe the bug:**
literally just title when trying to install a thing (any)

**To Reproduce:**
1. literally just try to download any app

**Expected behavior:**
i expected it to work

**Screenshots:**
no sorry

**Console:**
- [ ] 3DS
- [ ] 3DS XL
- [ ] 2DS
- [x] New 3DS (LL)
- [ ] New 3DS XL
- [ ] New 2DS XL

**Luma3DS & System versions:**

Luma 3DS version: 
10.2.1

System version and region: 
Region: Russia, system version just updated (12.14.21)

**Universal-Updater version:**

Release:
3.2.3

Nightly: 

Installed as:
- [ x] CIA
- [x ] 3DSX

**Additional context:**

**Comment by Epicpkmn11** [comment]
Weird, do you have a custom DNS or Proxy set? (ex. for Sudomemo or Wiimmfi) I think that'll break it.

Also make sure you've got space on your SD card.

**Comment by logixhot** [comment]
> Weird, do you have a custom DNS or Proxy set? (ex. for Sudomemo or Wiimmfi) I think that'll break it.
> 
> Also make sure you've got space on your SD card.

Not sure, the thing is that I got this as a gift from my brother.. I don't think theres any

**Comment by Epicpkmn11** [comment]
huh... Maybe try deleting the `sdmc:/3ds/Universal-Updater` folder, or at least renaming it, to see if that fixes it somehow

Maybe check in the web browser (on the 3DS) too to see if you can access https://db.universal-team.net, the certificate warning is fine as long as it can load the site it should work...

**Comment by logixhot** [comment]
> huh... Maybe try deleting the `sdmc:/3ds/Universal-Updater` folder, or at least renaming it, to see if that fixes it somehow

That fixed it, thanks alot!
