### ISSUE TITLE
[Feature Request] DaedalusX64 Update on the normal shop

### ISSUE THREAD

**Issue by cmod31** [Universal-Team/Universal-Updater#112]
**Is your feature request related to a problem? Please describe.**
The [DaedalusX64](https://github.com/masterfeizz/DaedalusX64-3DS) N64 emluator version on the Universal Updater shop is outdated.

**Describe the solution you'd like:**
Use my Release that i put on a fork of DaedalusX64
https://github.com/cmod31/DaedalusX64-3DS-archived/releases/tag/v0.4

**Additional context:**
The Release is from their official Discord wich got taken down and the repository owner is inactive on github since 2 years.
Also its very sad this thing had so much potential.

**Comment by SuperSaiyajinStackZ** [comment]
You should request it on [Universal-DB](https://github.com/Universal-Team/db) instead.

**Comment by cmod31** [comment]
thanks didn't found the repo
