### ISSUE TITLE
[Feature Request] Default search options

### ISSUE THREAD

**Issue by lifehackerhansol** [Universal-Team/Universal-Updater#113]
**Is your feature request related to a problem? Please describe.**
Currently when you open the titles section and you just type in the search bar, absolutely nothing happens. Usually one would expect results to just show up right away, and the tweak the filters if it doesn't.

With all checkboxes off by default, it almost appears as if the search is doing nothing at all, which can be a little confusing.

**Describe the solution you'd like:**
By default I think if anything is in the search bar, it should immediately search with all filters ON, and set to OR.
This doesn't need to be visibly enabled: if someone wants to search Titles only, then they can check the Title box, and then it switches to the filtered settings.

**Describe alternatives you've considered:**
Or just visibly display the default set options.

Point being, I think default settings should be made so that using the search bar immediately searches for an app.

**Comment by Epicpkmn11** [comment]
Already changed it in b907cd6b31e0eb93024755ef176f03e1826e74e4 lol, at least I think that solves this.

I just made it default to title, since yeah the old behaviour was weird lol
