### ISSUE TITLE
[Bug Report] Invalid Unistore

### ISSUE THREAD

**Issue by swaggio7** [Universal-Team/Universal-Updater#120]
**Describe the bug:**
I may be stupid and blind, but whenever I launch UniUpdater, it shows `Invalid UniStore` on the top screen. I went into Settings, Select UniStore, pressed the plus icon, then selected Universal-DB. When I went to the menu, it didn't show anything. Still said `Invalid UniStore`. Did this multiple times, reinstalled UniUpdater, and still nothing.

**To Reproduce:**
1. I don't know
2. 
3. 

**Expected behavior:**
Just thought it would load Universal DB.

**Screenshots:**
![Image](https://user-images.githubusercontent.com/87071118/166697916-2ccedc33-b495-4978-b94e-c35cb3d3a4a7.jpeg)

**Console:**
- [ ] 3DS
- [ ] 3DS XL
- [ ] 2DS
- [ ] New 3DS
- [ ] New 3DS XL
- [x] New 2DS XL

**Luma3DS & System versions:**

Luma 3DS version: 10.3

System version and region: 11.15.0-47U

**Universal-Updater version:**

Release: 3.2.5

Nightly: 

Installed as:
- [x] CIA
- [ ] 3DSX

**Additional context:**

**Comment by DJZSwag** [comment]
Strange... The Browser worked and the eShop also worked. I do not have a custom DNS set.

**Comment by DJZSwag** [comment]
Hello? It's been a month and I did not get any replies

**Comment by DJZSwag** [comment]
Still nothing...

**Comment by Epicpkmn11** [comment]
Sorry I'm just not sure what's wrong... You can download the unistore manually from: http://db.universal-team.net/unistore/universal-db.unistore, but that won't likely fix it permanently, might not even be able to download...

Have you tried deleting the connection in 3DS settings and re-adding it? Or maybe need to change some router setting, I'm just not sure...

**Comment by swaggio7** [comment]
Fixed a while ago.

**Comment by Salva2degatitos** [comment]
> Fixed a while ago.

I have the exact same problem. How could you explain how did you fix it?

**Comment by KendrickLamar2003** [comment]
> I have the exact same problem. How could you explain how did you fix it?

Im not really sure, it's been more than 2 years...

I recommend to just try reinstalling uniupdater (every folder and such related to it) and see if that works. If not, try starting a new issue.

**Comment by Salva2degatitos** [comment]
> > I have the exact same problem. How could you explain how did you fix it?
> 
> Im not really sure, it's been more than 2 years...
> 
> I recommend to just try reinstalling uniupdater (every folder and such related to it) and see if that works. If not, try starting a new issue.

Thanks
