### ISSUE TITLE
[Bug Report] I can not find "CPyMO" in Universal-Updater but I was found it on Website. (Maybe Universal-DB update doesn't work?)

### ISSUE THREAD

**Issue by Seng-Jik** [Universal-Team/Universal-Updater#122]
**Describe the bug:**
I can not find "CPyMO" in Universal Updater, but it is not display in Universal-DB.

**To Reproduce:**
1. Open Universal-Updater
2. Open search, and input "CPyMO"
3. I got no application to download.

**Expected behavior:**
* "CPyMO" displayed in Universal-Updater.
* "CPyMO" can download in Universal-Updater.

**Screenshots:**

![img](https://user-images.githubusercontent.com/11296891/170471011-991f21cb-73f3-4ecb-9bd2-8b143ce7cb1f.png)
![IMG_7781](https://user-images.githubusercontent.com/11296891/170470740-4ca50c52-39da-4708-b870-4d7c465c9a82.JPG)

**Console:**
- [ ] 3DS
- [ ] 3DS XL
- [ ] 2DS
- [x] New 3DS
- [ ] New 3DS XL
- [ ] New 2DS XL

**Luma3DS & System versions:**

Luma 3DS version: v10.2.1

System version and region: 

**Universal-Updater version:**

Release: v3.2.5

Nightly: 

Installed as:

- [x] CIA
- [ ] 3DSX

**Additional context:**
* I'm in China, sometimes my 3DS can not access github url.

**Comment by Seng-Jik** [comment]
I'm author of CPyMO.
Maybe I publish too much files on github release? but I has published the cia and 3dsx file.

**Comment by Seng-Jik** [comment]
Now I uninstall Universal-Update, delete `sdmc:/3ds/Universal-Updater`, and reinstall it, "CPyMO" displays on Universal-Updater.

Maybe Universal-Updater can not download latest universal-db?

**Comment by NightScript370** [comment]
> I'm in China, sometimes my 3DS can not access github url.

This may be the problem. If its working now, though, I think its just the consoles fault.

**Comment by Epicpkmn11** [comment]
I've switched the UniStore self links back to db.universal-team.net instead of the GitHub raw files, hopefully that should reduce this issue.

I switched them to point to the repo's files instead since it was causing issues in the DSi version, but as that's not being worked on at the moment that's not a big deal, it would ideally be fixed anyways.

---

On a different note, are there any usage notes on CPyMo anywhere? It would be nice to have same usage notes we could put on the Universal-DB page for how to install games for it and some examples of games it supports or such as tbh I have no clue how to use it... Ideally an English translation (and optionally Chinese too) for the site would be nice, though can always just Google Translate it if it's in Chinese.

**Comment by Seng-Jik** [comment]
> > I'm in China, sometimes my 3DS can not access github url.
> 
> This may be the problem. If its working now, though, I think its just the consoles fault.

Now I just reinstall Universal-Updater and clean cache, it works now, and my chinese friends has this problem too.

**Comment by Seng-Jik** [comment]
> I've switched the UniStore self links back to db.universal-team.net instead of the GitHub raw files, hopefully that should reduce this issue.
> 
> I switched them to point to the repo's files instead since it was causing issues in the DSi version, but as that's not being worked on at the moment that's not a big deal, it would ideally be fixed anyways.
> 
> On a different note, are there any usage notes on CPyMo anywhere? It would be nice to have same usage notes we could put on the Universal-DB page for how to install games for it and some examples of games it supports or such as tbh I have no clue how to use it... Ideally an English translation (and optionally Chinese too) for the site would be nice, though can always just Google Translate it if it's in Chinese.

PyMO games is mostly in Chinese, so I not compile the English version of CPyMO.

about CPyMO(Chinese): [github.com/Strra](https://github.com/Strrationalism/CPyMO/blob/main/README.md)
how to make game in PyMO: [PyMO Doc](https://www.pymogames.com/PYMO%E6%95%99%E7%A8%8B.pdf)

My English is limited, so I can't guarantee the availability of its English version, I make a simple English translation for CPyMO: [src](https://github.com/Strrationalism/CPyMO/blob/931812b8eb7b73d4f7db852378712f8148b72877/cpymo/cpymo_localization.c#L156)
