### ISSUE TITLE
[Bug Report] Compilation

### ISSUE THREAD

**Issue by Matrix1222** [Universal-Team/Universal-Updater#125]
Hi,
I have an error during the compilation : 
https://pastebin.com/9uMRnf7Z

**Comment by NightScript370** [comment]
Honestly, reading the log, this may be a problem with your setup. Try uninstalling and reinstalling the toolchain.

**Comment by Matrix1222** [comment]
How do I reinstall the tools, with which command ?

**Comment by Matrix1222** [comment]
I use this :
```pacman -S 3ds-dev 3ds-curl 3ds-bzip2 3ds-liblzma```
?

**Comment by Matrix1222** [comment]
I tried to reinstall the toolchain, but I still get the same error

**Comment by Matrix1222** [comment]
I just saw that in the Makefile by modifying :
CFLAGS	+=	$(INCLUDE) -D__3DS__ -D_GNU_SOURCE=1
By: 
CFLAGS	+=	$(INCLUDE) -DARM11 -D_3DS -D_GNU_SOURCE=1
It works
How does this happen?

**Comment by Epicpkmn11** [comment]
You must have an outdated libctru, that's the old CFLAGS.

Try running:
```bat
pacman -Sy 3ds-dev 3ds-curl 3ds-bzip2 3ds-liblzma
```

**Comment by Matrix1222** [comment]
Yes thanks
