### ISSUE TITLE
Ryukyuan language translation

### ISSUE THREAD

**Issue by kuragehimekurara1** [Universal-Team/Universal-Updater#130]
hello!  I would like to translate universal-updater into Ryukyuan languages. How should I translate it?

**Comment by Epicpkmn11** [comment]
Translation is done on Crowdin: https://crowdin.com/project/universal-updater

---

I don't see anything called "Ryukyuan" in the default language list, is there another name or what should I add it/them as?

(Ideally I need the English/romanized name, native name, locale code, and how plurals work. Locale code doesn't need to be standardized if there isn't one, just something to use for this)

![スクリーンショット 0004-08-04 18 09 36](https://user-images.githubusercontent.com/41608708/182970275-1353f21b-cb82-4fc0-9785-bfd47a39c158.png)
![スクリーンショット 0004-08-04 18 10 09](https://user-images.githubusercontent.com/41608708/182970279-a930ace8-dd4f-44ed-b2e8-af8e78aa4c4d.png)

**Comment by kuragehimekurara1** [comment]
Please add in Ryukyuan or 琉球諸語​​(Ryūkyū-shogo)

**Comment by Epicpkmn11** [comment]
Added 👍 

https://crowdin.com/project/universal-updater/ry

**Comment by kuragehimekurara1** [comment]
Thank you!

**Comment by kuragehimekurara1** [comment]
Translation of universal-updater is complete!  I would like to translate nds-bootstrap, TWiLight Menu++, GodMode9 and universal-DB into Ryukyuan languages, but is it possible to add languages ​​to Crowdin?
Also, I would like to ask PlicyVimeo#9957 to grant the Translators role.

**Comment by Epicpkmn11** [comment]
Added the language to UU with 101cb56036783eb9e589cf3bb9c7b0f68de286a1 👍 

I've added it to the other projects so you should be able to translate those now. I assume you meant GodMode9**i** as the original GodMode9 isn't translatable (yet, I was working on it though I've been a bit distracted lately... need to get back to that...)

For the translation role simply run the bot command `!togglerole Translators` on the server.

**Comment by kuragehimekurara1** [comment]
Thank you for adding it!  It's Godmode9i!  Sorry for the mistake.  Where should I run the post command?

**Comment by Epicpkmn11** [comment]
[#end-of-universe](https://discord.com/channels/568119817320792074/620406977490714626) is best for Universal-Server, if you're on DS⁽ⁱ⁾ Mode Hacking! as well then [#end-of-server](https://discord.com/channels/283769550611152897/283770736215195648) there.

**Comment by kuragehimekurara1** [comment]
Thank you!

**Comment by kuragehimekurara1** [comment]
The translations of nds-bootstrap, GodMode9i and universal-DB have been completed, so please add them!
