### ISSUE TITLE
[Bug Report] Add Unistore UI Bug

### ISSUE THREAD

**Issue by KorbinCode** [Universal-Team/Universal-Updater#132]
**Describe the bug:**
if there are too many options, some unistores wont appear in the add menu

**To Reproduce:**
1. Go to the "Switch Unistores" Menu
2. Add Unistores, Go all the way down
3. Realize that the Wordle DS Mods Unistore is off-screen, and the menu cannot scroll down.

**Expected behavior:**
The menu scrolls down.

**Screenshots:**

**Console:**
- [ ] 3DS
- [ ] 3DS XL
- [ ] 2DS
- [ ] New 3DS
- [x] New 3DS XL
- [ ] New 2DS XL

**Luma3DS & System versions:**

Luma 3DS version: 
10.3

System version and region: 
11.15.0-47U

**Universal-Updater version:**

Release: 
3.1.5

Nightly: 

Installed as:
- [x] CIA
- [ ] 3DSX

**Additional context:**

**Comment by Epicpkmn11** [comment]
This was fixed by ad10cb40fe27112b2c9d0b5a90c12bd5b321bbf8, we just haven't gotten around to a new release since not all that much has changed

Could probably do a release soon though, not much else in the plans at the moment and there is that fix
