### ISSUE TITLE
delete https://github.com/Universal-Team/Universal-Updater/issues/133 (it's just a troll page) along with deleting this issue too just like how https://github.com/Difegue/DoujinSoft/issues/26 and some openemu issues are actually deleted.

### ISSUE THREAD

**Issue by ghost** [Universal-Team/Universal-Updater#139]
this troll page needs to be deleted https://github.com/Universal-Team/Universal-Updater/issues/133, much like https://github.com/Difegue/DoujinSoft/issues/26 and plenty of openemu deleted issues.
[warioware ds - clean no cheats-progress saves with the dlc and wii content in nds's .dsv drastic form.zip](https://github.com/Universal-Team/Universal-Updater/files/11007757/warioware.ds.-.clean.no.cheats-progress.saves.with.the.dlc.and.wii.content.in.nds.s.dsv.drastic.form.zip)
[warioware ds - clean no cheats-progress saves with the dlc and wii content in nds's .sav real hardware form.zip](https://github.com/Universal-Team/Universal-Updater/files/11007758/warioware.ds.-.clean.no.cheats-progress.saves.with.the.dlc.and.wii.content.in.nds.s.sav.real.hardware.form.zip)

**Comment by NightScript370** [comment]
Seems like the only troll here is you. Goodbye, and enjoy your history.
