### ISSUE TITLE
[Bug Report] UU locking up when closing

### ISSUE THREAD

**Issue by TwystedXYZ** [Universal-Team/Universal-Updater#142]
**Describe the bug:**
Using the latest nightly causes UU to softlock or crash entirely upon pressing START to exit.

**To Reproduce:**
1. Use the latest public nightly of UU
2. Launch
3. Either single-press or rapidly double-press START

**Expected behavior:**
Exit to HOME menu without hanging.

**Screenshots:**

**Console:**
- [ ] 3DS
- [ ] 3DS XL
- [x] 2DS
- [ ] New 3DS
- [ ] New 3DS XL
- [x] New 2DS XL

**Luma3DS & System versions:**

Luma 3DS version: 
12.0.1-3gxldr, newest build for CTGP-7

System version and region: 
11.17.0-50U

**Universal-Updater version:**

Release: 
nightly

Nightly: 
8abd321

Installed as:
- [x] CIA
- [ ] 3DSX

**Additional context:**
Double-pressing START used to make UU exit faster by skipping the fade-out.

**Comment by TwystedXYZ** [comment]
Sent this FROM the n2dsxl experiencing the bug, since it can somehow do this.

**Comment by Komas19-new** [comment]
can confirm for luma 13.0.1

**Comment by Neucher** [comment]
same issue 13.0.2

**Comment by Barrettloganj13** [comment]
can comfirm for old 3DS

**Comment by Epicpkmn11** [comment]
Should be fixed, see devkitPro/libctru#534

**Comment by Barrettloganj13** [comment]
yes it has been fixed thanks
