### ISSUE TITLE
[Bug Report] Outdated translations

### ISSUE THREAD

**Issue by H0mebrewL0ver** [Universal-Team/Universal-Updater#154]
**Describe the bug:**
Over the last two years, there have been a number of improvements to various localizations. Since you have recently released a new version, would it be possible to create a new version with updated translations in the future?

**Expected behavior:**
Updated translations with the new release.

**Console:**
- [x] 3DS

**Universal-Updater version:**

Release: 3.2.7

Installed as:
- [x] CIA
- [ ] 3DSX

**Comment by lifehackerhansol** [comment]
Thank you for the reminder. v3.2.8 was released with the new translation updates.
