### ISSUE TITLE
[Bug Report]  Vapecord script out of date

### ISSUE THREAD

**Issue by Geezus42** [Universal-Team/Universal-Updater#22]
**Describe the bug**
Vapcord script installs version 1.4.1, current is 1.5.1

https://github.com/RedShyGuy/Vapecord-ACNL-Plugin/releases/tag/v1.5.1

**To Reproduce**
run Vapecord script

**Expected behavior**
Install version 1.5.1

**Console/Version (please complete the following information):**

  Console :

  - [ ] 3DS
  - [ x] 3DS XL
  - [ ] 2DS
  - [ ] New 3DS
  - [ ] New 3DS XL
  - [ ] New 2DS XL

  Luma & System version:

Luma 3DS version  v10.0.1
System version & Region v11.13.0-45U

**Universal-Updater (please complete the following information):**
  - [ x] Release

If Release -> version [example: v2.3.1

  How do you launch it:

  - [x ] cia
  - [ ] 3dsx

**Additional context**
couldn't find where you pull the scripts from so I could make the change and open a pull request

**Comment by SuperSaiyajinStackZ** [comment]
I haven't looked much at Scripts yet, but [here](https://github.com/Universal-Team/Universal-Updater-Scripts/blob/master/Vapecord-Plugin.json) is a link to the script, in case you like to fix it.

**Comment by Geezus42** [comment]
Pull request

https://github.com/Universal-Team/Universal-Updater-Scripts/pull/1

**Comment by SuperSaiyajinStackZ** [comment]
Pull Request merged. Closing this Issue now.

**Comment by Geezus42** [comment]
It's still not installing the current version. Apparently I still don't know what I'm doing.

**Comment by SuperSaiyajinStackZ** [comment]
If it says v1.5.0, it's the Plugin Creator's fault. They forgot to update the Version which is displayed.

**Comment by Geezus42** [comment]
Where do you see that?

**Comment by SuperSaiyajinStackZ** [comment]
You load up the Plugin and then you'll press `SELECT` when it says "Plugin ready!" or something. It'll Display it like `[1.5.0]` on the Top Screen then. This has nothing to do with Universal-Updater anymore.

**Comment by Geezus42** [comment]
Mine shows 1.4.1 but ok.

**Comment by SuperSaiyajinStackZ** [comment]
Make sure to delete the old Plugin stuff then and make sure you updated the Script from `Get Scripts`. You might rely on a old Script Version on your SD Card and it tries to load it instead. This is going out of scope from Universal-Updater completely though.

**Comment by Geezus42** [comment]
Will do. Thanks for looking.
