### ISSUE TITLE
Greyscale Screen when loading NTR/TWL Script

### ISSUE THREAD

**Issue by RedNova888** [Universal-Team/Universal-Updater#25]
When I go into the menu to use the NTR/TWL update script, the menu goes into grey-scale like in the screenshot. None of my other script menus do this. Why is this?

  - [X] New 2DS XL
Luma 3DS version [10.0.1-c913de1]
System version & Region [11.13.0-45U]
  - [X] Release - v2.3.1
  - [X] cia

![2020-04-08_16-32-11 825_top](https://user-images.githubusercontent.com/30453795/78938529-a071ea00-7a6f-11ea-96bb-6cac984a4482.jpg)

![2020-04-08_16-32-11 825_bot](https://user-images.githubusercontent.com/30453795/78938546-a667cb00-7a6f-11ea-82e7-e4d3098269ac.jpg)

**Comment by SuperSaiyajinStackZ** [comment]
That's normal. That's the Script's Color.
