### ISSUE TITLE
Option to remove apps [Feature Request]

### ISSUE THREAD

**Issue by wuniversales** [Universal-Team/Universal-Updater#26]
It would be great to add an option to remove the applications, in my case I am running out of space on the card, and I have to manually uninstall from the computer. 

Why not add an option to delete from an application?

Thanks greetings

**Comment by SuperSaiyajinStackZ** [comment]
It's already implemented, but it will get removed with the next Version cause People can basically easilly destroy their console with that. FBI is a better tool to remove apps.

**Comment by SuperSaiyajinStackZ** [comment]
Closing this, because this will never be a thing for Universal-Updater anymore. Please use FBI for removing apps.
