### ISSUE TITLE
Problem with making a store

### ISSUE THREAD

**Issue by L-i-n-u-x-C-a-t** [Universal-Team/Universal-Updater#30]
Hi. So i was trying to make a unistore that could link to my projects and it looks like i did something wrong because when i load it in the app it says "MISSING : storeInfo". However, i have a storeInfo in my file. i won't copy paste the code but you can found it on [my github](https://github.com/L-i-n-u-x-C-a-t/LinuxCat-s-Store/blob/master/unistore/linuxcat-store.unistore). If you can help me, i'll be thankful.

**Comment by SuperSaiyajinStackie** [comment]
Remove the comma at:
Line 46 by description at the end.
Line 60 by description at the end.
Line 67 by the `],}`.

After it it should work.

**Comment by SuperSaiyajinStackie** [comment]
You also forgot `"fileSize"` on the info part for each entry. Just set it to `0` to make it "unknown" or so.

**Comment by L-i-n-u-x-C-a-t** [comment]
thanks, i'll see if it works.

**Comment by L-i-n-u-x-C-a-t** [comment]
it works, thanks again. closing the issue now.
