### ISSUE TITLE
TinyDB store dead?

### ISSUE THREAD

**Issue by Hundifan33** [Universal-Team/Universal-Updater#34]
TinyDB website cant be reached anymore, the TinyDB button in the Store search menu will just lead to a download failed message, (it will still write a corrupt store to the store list, which has to be deleted) 

Try to install the TinyDB store via the "UniStore"->"Store Search"->"TinyDB" Button.

  Console :
  - [X] 2DS
Luma 3DS version v10.1.3
System version & Region v11.13.0-45E

**Universal-Updater (please complete the following information):**
  - [X] Release (2.4.0)
  - [X] cia

**Comment by SuperSaiyajinStackie** [comment]
Yes, TinyDB is down Right now.

**Comment by SuperSaiyajinStackie** [comment]
If you want to be notified when it's up again, feel free to join our discord Server. (The link should be in the ReadMe iirc.)
