### ISSUE TITLE
Force close

### ISSUE THREAD

**Issue by Janvicttor** [Universal-Team/Universal-Updater#39]
When I open the app, they load for some time in a blue screen writen "homebrew" and force close after 2~3 seconds.

I don't receive any error code or message, the app only close and I return to my homescreen.

Console:
-NEW 3DS XL
-Ver 11.13.0-45U
-Luma 10.0.1

Universal Updater:
-2.5.0

**Comment by Janvicttor** [comment]
Att: I update Luma to the v10.1.3 and force close continues.

**Comment by NightYoshi370** [comment]
Delete Settings.json from sdmc:/3ds/Universal Updater
