### ISSUE TITLE
[Feature Request]Request for delete my eshop alternati

### ISSUE THREAD

**Issue by Ghost0159** [Universal-Team/Universal-Updater#43]

**Comment by Ghost0159** [comment]
I am thinking with other developer is former developer whose name I will not locate for the moment see ever if he wishes, has a homebrew using this script is so that this script is not accessible for Universal-Updater, as well as no affiliation with Universal-Team.
In the meantime, I take all responsibility for this script and will continue to improve it.
Thanks for Universal-Updater, continued like this, I swear to find a solution within 2 weeks or even 1 month.
Regards Ghost0159

**Comment by XDgierman** [comment]
Piracy is condemned on U-U. Your files contain links to dropbox files. What you are saying is not an excuse to use U-U to propagate piracy on 3DS.

**Comment by Ghost0159** [comment]
I absolutely agree, that's why I'm looking for a solution with other developers.

**Comment by SuperSaiyajinStackZ** [comment]
Just so y'know, Piracy is a big NO in the Homebrew scene. I do suggest to take down what you did. The only solution is to remove that piracy crap.

**Comment by Ghost0159** [comment]
I don't want to delete it, but turn it into a unique homebrew.
I will not go back on this decision.
PS: There is a replacement for tinydb: http://macrodb.tk/

**Comment by NightYoshi370** [comment]
1. You really need to express better English skills. It's kind of hard to read your messages
2. What you do with UU stores isn't controlled by the Universal Team. That is the very nature of stores.
However, we can still ask you to atleast respect our viewpoints of how UU should be, and take it down.
3. Turn it into your own homebrew? Very well. However, if you use UT stuff as a base, please make it absolutely clear that we are not affiliated.
We cannot control what you do outside UU but we could still retain our public image.
4. I'm not sure why an issue here was made. Why bring the stuff here? What piracy bullcrap you do has nothing to do with UU.

I'm closing this, and XDGierman, you're not a mod so stop backseat moderating.
