### ISSUE TITLE
[Bug Report] CTGP-7 installation script doesn't work.

### ISSUE THREAD

**Issue by mariohackandglitch** [Universal-Team/Universal-Updater#47]
**Describe the bug**
Trying to run the CTGP-7 installation script causes the download to fail. It never finishes downloading the files (Step 1/5) and the script execution is aborted. After the abort, it automatically returns to the select .cia or .3dsx install option. After checking the SD, it can be seen that the file has only downloaded partially. (CTGP7installtemp folder on the root)

**To Reproduce**
Run the CTGP-7 install script, select .cia option. After a while of downloading, it will abort.

**Expected behavior**
The script should complete normally.

**Screenshots**

**Console/Version (please complete the following information):**

  Console :

  - [x] 3DS
  - [x] 3DS XL
  - [ ] 2DS
  - [ ] New 3DS
  - [x] New 3DS XL
  - [ ] New 2DS XL

  Luma & System version:

Luma 3DS version v10.2
System version & Region v11.13.0-45E (latest)

**Universal-Updater (please complete the following information):**
  - [x] Release

If Release -> v2.5.1

  - [x] Nightly

If Nightly -> fb6896c593b590f8ffa5337e358f970745544e6d

  How do you launch it:

  - [x] cia
  - [ ] 3dsx

**Additional context**

**Comment by SuperSaiyajinStackZ** [comment]
Closing this, because Universal-Updater v3 is gonna be a thing in the coming days and removes script functionality. The script got removed on request as well, so i think closing this is fine.
