### ISSUE TITLE
[Bug Report] Multiple GUI weirdness

### ISSUE THREAD

**Issue by vargaviktor** [Universal-Team/Universal-Updater#52]
**Describe the bug**
Navigation neither works with analog stick neither with d-pad on multiple screens. (tested on an o3ds xl)
1. Language select: only bruh and danks selectable sometimes, touching also not works.
2. Selecting stores: sometimes d-pad and analog is ok for one move. touching the arrows on right side is working
same is appliable for the other view

**To Reproduce**
Open the screens mentioned and try to navigate.

**Expected behavior**
1. More than one language should possible to choose.
2.  Should possible to navigate with d-pad and analog stick too.

**Console/Version (please complete the following information):**

  Console :

  - [ ] 3DS
  - [x ] 3DS XL
  - [ ] 2DS
  - [ ] New 3DS
  - [ ] New 3DS XL
  - [ ] New 2DS XL

  Luma & System version:

Luma 3DS version v10.2
System version & Region v11.13.0-45E

**Universal-Updater (please complete the following information):**
  - [ x] Release

If Release -> version  2.5.1

  - [ ] Nightly

If Nightly -> Commit hash [example: a10b9da]

  How do you launch it:

  - [x ] cia
  - [ ] 3dsx

**Additional context**
I am trapped in the danks language now. :)

**Comment by SuperSaiyajinStackZ** [comment]
Might be fixed with v3.0.0's complete rewrite which will be released soon. Tho i never had this issue before.

**Comment by SuperSaiyajinStackZ** [comment]
Ah, touch does not work there on the Language selection, since i was too lazy and forgot to add it, but i still cannot reproduce your D-Pad issues tho. v3.0.0 will change the complete Universal-Updater and it's behaviors (See ReadMe for screenshots), since it's a full rewrite. Maybe report back then, if it still doesn't work when it's out next week.

**Comment by vargaviktor** [comment]
MarkMenu.png is my favourite. Will try the new release.
