### ISSUE TITLE
[Feature Request] Add to the queue

### ISSUE THREAD

**Issue by wuniversales** [Universal-Team/Universal-Updater#55]
**Is your feature request related to a problem?**
The problem is that you cannot perform multiple installations in queue.

**Describe the solution you'd like**
I would like to be able to explore the content of the store while I download some content from it.
Also, being able to add other facilities to the queue.

**Describe alternatives you've considered**
I propose to make the following changes:
- Being able to explore the store while downloads and installations are taking place in the background.
- To be able to "Add to the queue" other contents of the store to download and install them.
- Block the "Exit" button when an installation is in progress in the background and reactivate when the queue ends.

I do not know if technically it can be done, but the application will improve a lot with that change.

**Comment by SuperSaiyajinStackZ** [comment]
That seems like a nice idea, but honestly, i am not sure how well it could be implemented. I will think about it, but no promises though.
