### ISSUE TITLE
[Bug Report] In Grid view, after quick donw scroll anf page switch, the icons will shifted to other app

### ISSUE THREAD

**Issue by vargaviktor** [Universal-Team/Universal-Updater#58]
**Describe the bug**
In Grid view, after quick donw scroll anf page switch, the icons will shifted to other app

**To Reproduce**
1. switch to gridview
2. hold down on the dpad, until you are on the last item
3. your selected item in the last row was hidden, and its icon will be shifted up with one row

**Expected behavior**
Should not have shifted with a line

**Screenshots**

**Console/Version (please complete the following information):**

  Console :

  - [ ] 3DS
  - [ ] 3DS XL
  - [ ] 2DS
  - [ ] New 3DS
  - [x ] New 3DS XL
  - [ ] New 2DS XL

  Luma & System version:

Luma 3DS version [v10.2.1]
System version & Region [v11.13.0-45E]

**Universal-Updater (please complete the following information):**
  - [x ] Release

version [v3.0.0]

  How do you launch it:

  - [ x] cia
  - [ ] 3dsx

**Comment by SuperSaiyajinStackZ** [comment]
Should be fixed with the latest commit.
