### ISSUE TITLE
[Feature Request] Add QR Code details to wiki

### ISSUE THREAD

**Issue by vargaviktor** [Universal-Team/Universal-Updater#59]
**Is your feature request related to a problem? Please describe.**
Without documentation i tried QR code URL to add a Unistore, but it killed the Universal Updater.

**Describe the solution you'd like**
Some documentation what to include into the QR will be cool.

**Comment by SuperSaiyajinStackZ** [comment]
Define "killed". What happened exactly? An Exception error occured?

Also well.. it should be obvious tbh, that the QR Code should contain the URL to the UniStore.

**Comment by vargaviktor** [comment]
An exception occured.
I thought, that maybe I missed the format, and its not in the docs. 
However I found out later, that the JSON was faulty and my bet on the URL was right.

**Comment by Epicpkmn11** [comment]
This seems to be done? So I'm going to close this issue
