### ISSUE TITLE
[Feature Request] Batch updating

### ISSUE THREAD

**Issue by willis936** [Universal-Team/Universal-Updater#62]
**Is your feature request related to a problem? Please describe.**
Add batch update feature, similar to how MultiUpdater works (right trigger on the list marks all for update).

**Describe the solution you'd like**
A way to update/install all currently filtered entries in the store.  A list of store entries to quickly update can be made by labeling store entries with an icon (such as star) then filtering to that icon and running the batch update operation.

**Describe alternatives you've considered**
Allowing for a markup language defined list of specific update procedures (exactly how multiupdater works).
Manually updating each store entry (current solution, cumbersome).

**Additional context**
Multiupdater is no longer maintained and it had great functionality.  It would be nice to see its primary feature integrated into the currently maintained 3ds updater.  See the final issue on its repo:
https://github.com/LiquidFenrir/MultiUpdater/issues/66

**Comment by Epicpkmn11** [comment]
Something similar, or at least that can help lead to this, is actually already in progress with the [queue-system](https://github.com/Universal-Team/Universal-Updater/tree/queue-system) branch which lets you continue using other parts of the app and queuing other downloads and such while an install is running, it's just got a bit of crashing at the moment for some reason iirc.

After the queue system stuff is stable we could maybe try adding an update all kinda thing, would probably just need to add tracking which entry you last installed and to ask which you want for new things, then just add them all to the queue.
