### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by caydenpri44** [Universal-Team/Universal-Updater#70]
Could you add Cyanogenmod3DS to the unistore I tried reuploading it to github and typing the download links but you can only download 3dsx and cia files via FBI. I can't download the required smdh and other system files needed for the application via the download link.
https://gbatemp.net/threads/cyanogen3ds-an-alternative-gui-menu-for-the-3ds.385401/

**Comment by Epicpkmn11** [comment]
It's from 2016 and both the Google Drive download and GitHub repo seem to have been deleted, does it even still work if you did find a download?

Also this belongs in [Universal-Team/db](https://github.com/Universal-Team/db), but please don't open up an issue just asking us to find the downloads to some old homebrew for you, if you want it added at least make sure it still works and can be downloaded and such.

**Comment by caydenpri44** [comment]
It still works my friend tested it.

**Comment by SuperSaiyajinStackZ** [comment]
As Epicpkmn11 already said, this does not belong to Universal-Updater. This repo is for the Universal-Updater app itself such as it's features and not for the UniStore's itself. This belongs in Universal-DB, which Epicpkmn11 linked in the comment.

**Comment by NightYoshi370** [comment]
> It still works my friend tested it.
This wasn't the only requirement listed for an issue to be here.

Also, if it still works, why aren't you able to fully send it over?
