### ISSUE TITLE
Simple and easier to make a unistore

### ISSUE THREAD

**Issue by spinkleboi** [Universal-Team/Universal-Updater#71]
Hello, it would be nice if we had a more easy way or to make it more clear to make your own unistore.

It would nice if you could have a video guide or even a UI for Computers to make you're own unistore

You see I would like to have a unistore where I can so I can instantly access them as I have a small SD card and I uninstall and reinstall games a lot and I could benefit from that.

Hope you reply soon.

**Comment by SuperSaiyajinStackZ** [comment]
The wiki to me sounds clear enough to be honest; Also looking into existing UniStore's for reference isn't too hard too.

Also; Video guides sounds like a bad idea, because those get outdated too quickly and just aren't the way to go.

*Maybe* an UI based UniStore Creator could be made in HTML, JS and CSS, tho that's not planned soon or so.

**Comment by spinkleboi** [comment]
Ok well could you help me and give me an example to work off of for that because it is very hard I don't know much about JSON in general

**Comment by SuperSaiyajinStackZ** [comment]
An example can be found here: https://github.com/Universal-Team/Universal-Updater/wiki/unistore-example.

**Comment by spinkleboi** [comment]
How do I use the file
do I use google drive to make it download to the system the unistore

**Comment by spinkleboi** [comment]
and also could I join the discord server (spinkleboi)#0159 thank you

**Comment by SuperSaiyajinStackZ** [comment]
You place the file into `sdmc:/3ds/Universal-Updater/stores/`. It must have the extension `.unistore` to get detected though.

**Comment by spinkleboi** [comment]
Ok thank you but can I get into the discord server?

**Comment by SuperSaiyajinStackZ** [comment]
You'll have to wait for now.

**Comment by spinkleboi** [comment]
Ok, thanks  ^-^
