### ISSUE TITLE
[Bug Report] Unable to build from source

### ISSUE THREAD

**Issue by lividhen** [Universal-Team/Universal-Updater#79]
**Describe the bug**
I am unable to build from source do to a missing file:
fatal error: screenCommon.hpp: No such file or directory

**To Reproduce**
1. Setup devkitpro
2. Put bannertool and makerom in path
3. Install dependencies listed in README
4. Run "make" in the universal updater source dir.

**Expected behavior**
It completes the build normally.

**Screenshots**
![error](https://user-images.githubusercontent.com/42221797/112736636-e7275100-8f19-11eb-82ae-b1b2fc2a1cb1.png)

**Console/Version (please complete the following information):**
 N/A

**Universal-Updater (please complete the following information):**
  - [ ] Release

If Release -> version [example: v2.2.0]

  - [x] Nightly
 (I suppose)
If Nightly -> Commit hash [example: a10b9da]
4c792a1ea0a78f97159ecad8e68d0bd0a8925430

  How do you launch it:
 N/A

**Additional context**
Im on windows
I cannot find a screenCommon.hpp in universal's source or my devkitpro directory

**Comment by SuperSaiyajinStackZ** [comment]
You didn't pulled the Universal-Core submodule. Check the README.md on how to do it.

**Comment by SuperSaiyajinStackZ** [comment]
Ah nevermind. I thought there were instructions about how to pull the submodule. Well, then run `git submodule update --init --recursive` i guess and it should work.

**Comment by lividhen** [comment]
OH! Thank you. I didn't realize there were submodules.

**Comment by Epicpkmn11** [comment]
Did you install `3ds-curl` in pacman?

**Comment by lividhen** [comment]
Yes. I will try uninstalling then reinstalling

**Comment by lividhen** [comment]
Okay, that worked. Now it seems to be stuck at the end with:
```
linking Universal-Updater.elf
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld.exe: cannot find -lbz2
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld.exe: cannot find -llzma
collect2.exe: error: ld returned 1 exit status
```

I have tried reinstalling libbz2 and bzip2 (which i think llzma is from, right?), but cant get it to change... 
Normally i can figure this kind of thing out... This is making me feel really incompetent 🤣

**Comment by Epicpkmn11** [comment]
Hmm, try running
```bash
(sudo dkp-)pacman -S 3ds-bzip2 3ds-libarchive 3ds-liblzma 3ds-mbedtls 3ds-zlib
```
(the sudo-dkp may not be needed depending on your OS)

I'm not sure if all of those are needed, but looking at what I have installed and what's in the Makefile I think you need at least some of those (notably `3ds-bzip2` and `3ds-liblzma` from your error)

**Comment by lividhen** [comment]
Thank you for all the help! I didnt realize I needed to use the 3ds specific libraries 😅
I have not used devkitpro much before.
