### ISSUE TITLE
[Feature Request] option to keep archive

### ISSUE THREAD

**Issue by GingkathFox** [Universal-Team/Universal-Updater#80]
**Is your feature request related to a problem? Please describe.**
One of the issues i have sometimes is when i need a file related to a app and UU doesn't extract it. I would like to be able to keep the archive to manually extract the files needed.

**Describe the solution you'd like**
maybe a prompt after downloading to keep the archive? or a option in the settings? Both would be best tbh.

**Comment by Epicpkmn11** [comment]
Is there something specific that it should be extracting that it isn't? I could fix that on Universal-DB's side if so, I haven't actually tested the majority beyond that they extract the files I tell them to to the right places 😅

I suppose an option to disable deleting might not be a bad idea though, just not sure how useful it is really... Universal-Updater should get everything important so it's missing something important we can fix that.

**Comment by GingkathFox** [comment]
Its just some files that the Orchestrina app needs that it cant download, and those are packaged in the zip

**Comment by Epicpkmn11** [comment]
What does it need? I just took a look at its zip and it's just:
```
   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2017-03-29 20:43:38 D....            0            0  3ds-arm
2017-03-29 17:51:29 D....            0            0  3ds-arm/3ds
2017-03-29 17:51:29 D....            0            0  3ds-arm/3ds/Orchestrina
2017-03-29 20:43:39 .....      7500880      5760084  3ds-arm/3ds/Orchestrina/Orchestrina.3dsx
2017-03-29 20:43:44 .....      7290880      7274528  3ds-arm/Orchestrina.3ds
2017-03-29 20:43:49 .....      7304128      6012644  3ds-arm/Orchestrina.cia
2017-03-29 20:43:38 .....      3270956      1226140  3ds-arm/Orchestrina.elf
------------------- ----- ------------ ------------  ------------------------
2017-03-29 20:43:49           25366844     20273396  4 files, 3 folders
```

I don't see anything else there that should need to be extracted...

**Comment by GingkathFox** [comment]
> For both versions, you will need an internet connection on your 3DS to download songs on first launch, else you may manually download the source code and copy and data/ into sdmc:/3ds/Orchestrina. Launch with your launcher of choice or from the home menu if using CIA, and enjoy!

maybe a option to download the repo .zip?

**Comment by Epicpkmn11** [comment]
Added downloading the songs on Universal-DB's side, it was a bit annoying since Orchestrina requires the song files with spaces (`Ballad of Gales.pcm`) but they use hyphens in the repo (`Ballad-of-Gales.pcm`) so I just made UU download each song on it's own to the correct path

**Comment by GingkathFox** [comment]
oki, thanks :D
