### ISSUE TITLE
[Bug Report] Compilation

### ISSUE THREAD

**Issue by Triwlo** [Universal-Team/Universal-Updater#82]
**Describe the bug**
*A clear and concise description of what the bug is.*
Hello, it makes it impossible to compile, it shows me that I am missing version.hpp, except I prefer to compile homebrew to be sure of the code, before installing them.

**To Reproduce**
*Steps to reproduce the behavior:*
Clone the repositery with git and then compile it with the libraries installed

**Expected behavior**
*A clear and concise description of what you expected to happen.*
That in the readme you tell us how to generate this.hpp version or how to do it or have it]

**Comment by Epicpkmn11** [comment]
It should be created automatically by the Makefile, I'm not sure why it wouldn't be...

https://github.com/Universal-Team/Universal-Updater/blob/master/Makefile#L64

I guess you could make it at with the following manually:
```cpp
#ifndef VERSION_HPP
#define VERSION_HPP

#define VER_NUMBER "v3.2.1-2b4e67e"

#endif
```

**Comment by Triwlo** [comment]
Weird that he didn't create it for me, thank you anyway
