### ISSUE TITLE
[Bug Report] compile

### ISSUE THREAD

**Issue by pirax378** [Universal-Team/Universal-Updater#86]
Hi;

I can't compile, could you help me please?

The error :
linking Universal-updater.elf
built ... Universal-Updater.smdh
/bin/sh/: line 1: bannertool.exe: command not found
make[1]: *** [/home/Pirax/Universal-Updater/Makefile:265: /home/Pirax/Universal-Updater/Universal-Updater.cia] Error 127
make: *** [Makefile:227: all] Error 2

Thanks for your help

**Comment by Epicpkmn11** [comment]
It's in the README.md, you need [bannertool](https://github.com/Steveice10/bannertool/releases/latest) in your PATH
