### ISSUE TITLE
Change Language in Settings?

### ISSUE THREAD

**Issue by mediocrejim** [Universal-Team/Universal-Updater#88]
I'm currently working with a Japanese 3DS LL that I've converted to English using CTRTransfer.
Unfortunately when using Universal Updater it seems to be defaulting to Japanese.

I have tried making sure the region in the 3DS settings is set to USA and I've selected my home state but it doesn't seem to make a difference within universal updater.

The ability to choose the language or region within the updater would be amazing.

Thank you!

**Comment by Epicpkmn11** [comment]
Universal-Updater remember's the system language from the first time it was opened as people don't usually change their language so it works fine most of the time.

You can already change the language in app, just go to settings (last item in the sidebar) -> Language (言語, first item) and choose the one you want.

**Comment by mediocrejim** [comment]
I see it now, the app I was using to translate mis-guided me a bit.  
Thank you for your quick reply and your time!
