### ISSUE TITLE
[Bug Report] ARM9: data abort

### ISSUE THREAD

**Issue by Natemo6348** [Universal-Team/Universal-Updater#99]
**Describe the bug:** So I'm not sure what caused this, but now every time I try to open universal-updater (or scroll over it) I get an arm9: data abort error from luma. Tried to remove it, but that results in the same error. Any ideas on why this could be happening and how it can be fixed?

**To Reproduce:**
1.  turn on console
2. scroll over or try to remove universal updater
3. get arm9 data abort error

**Expected behavior:** should be able to open it as usual

**Screenshots:**

**Console:**
- [ ] 3DS
- [x] 3DS XL
- [ ] 2DS
- [ ] New 3DS
- [ ] New 3DS XL
- [ ] New 2DS XL

**Luma3DS & System versions:**

Luma 3DS version:  10.2.1

System version and region:  11.15.0-47U

**Universal-Updater version:**

Release: 3.2.2

Nightly: 

Installed as:
- [x] CIA
- [ ] 3DSX

**Additional context:**

**Comment by Epicpkmn11** [comment]
Hmm, this is on the HOME Menu? Sounds like your SD card might be dying if so, maybe try backing up your files, formatting, and running a test on it: https://dsi.cfw.guide/sd-card-setup (this is the DSi guide, but I don't think the 3DS guide has instructions on checking for errors and it's the same for both)

**Comment by Natemo6348** [comment]
> Hmm, this is on the HOME Menu? Sounds like your SD card might be dying if so, maybe try backing up your files, formatting, and running a test on it: https://dsi.cfw.guide/sd-card-setup (this is the DSi guide, but I don't think the 3DS guide has instructions on checking for errors and it's the same for both)
> 
> Edit: Or possibly just corruption but the SD card isn't dying which is why it's good to run the test, still sounds like somehow something is corrupted.

Ok thank you, I'll try that and see if that fixes it!

**Comment by Natemo6348** [comment]
Ok, I ran the check on my SD card and it's completely fine, so I tried re-installing universal updater, and it works now
